### ISSUE TITLE
Lag Data Not Integer

### ISSUE THREAD

**Issue by chehadekassouf** [HassanEmam/PyP6Xer#21]
Hi @HassanEmam 
There are some XER files where lag value is a decimal like 0.08 or -0.8
The import is raising a conversion error

**Comment by MB-Lox** [comment]
I could solve it, with this line of code in "taskred.py". Maybe you'll add in to any future release
        if lag_hr_cnt:
            lag_hr_cnt = lag_hr_cnt.strip()
            if isinstance(lag_hr_cnt, int):
                self.lag_hr_cnt = lag_hr_cnt
            else:
                self.lag_hr_cnt = int(round(float(lag_hr_cnt)))
        else:
            self.lag_hr_cnt = None

**Comment by HassanEmam** [comment]
I am not sure why you reckon this is an issue. 

All calculations in XER files are done based on the hours per day and when you do get a fraction as 0.08 this shows that there is an issue with the programme development not with the library.

@MB-Lox your code will code but this is not the fix. In my view the schedule need to be fixed rather than rounding off.

In my experience, these issues are often caused by calendars. Either using multiple calendars in an incorrect way or changing calendars settings after allocation to activities.
